# Generated by Django 5.2.17 on 2026-09-24 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_sensitive', models.BooleanField(default=False, help_text='High-risk permission; assignment is audited.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['module', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.PositiveSmallIntegerField(default=50, help_text='Authority rank (0-100). Higher ranks may manage lower ones.')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded from the specification; cannot be deleted.')),
                ('is_platform', models.BooleanField(default=False, help_text='Only grantable outside an organization (platform staff).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Empty for system-wide roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='security.permission')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Empty only for platform-scoped roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='security.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, help_text='Empty = all warehouses in the organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'role assignment',
                'verbose_name_plural': 'role assignments',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_role_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='unique_system_role_code'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'organization'], name='security_ro_user_id_cd1fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'warehouse'], name='security_ro_user_id_aa431c_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'organization', 'warehouse'), name='unique_role_assignment_scope'),
        ),
    ]
