# Generated by Django 5.2.17 on 2026-09-24 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('security', '0002_seed_rbac_registry'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='unique_role_assignment_scope',
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('user', 'role', 'organization'), name='unique_assignment_org_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('user', 'role', 'organization', 'warehouse'), name='unique_assignment_warehouse_scope'),
        ),
    ]
