# Generated by Django 5.2.17 on 2026-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_assignment_scope_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Grant paused because the account was deactivated. Reactivating the account restores exactly this grant; deliberate revocation does not.'),
        ),
    ]
