# Generated by Django 5.2.17 on 2026-09-24 15:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Use 2-32 characters: A-Z, 0-9, dash or underscore.', regex='^[A-Z0-9][A-Z0-9\\-_]{1,31}$')])),
                ('name', models.CharField(max_length=150)),
                ('warehouse_type', models.CharField(choices=[('distribution', 'Distribution center'), ('fulfillment', 'Fulfilment center'), ('cross_dock', 'Cross-dock'), ('cold_storage', 'Cold storage'), ('bonded', 'Bonded warehouse')], default='distribution', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='organizations.branch')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouses',
                'ordering': ['branch__organization__name', 'code'],
                'indexes': [models.Index(fields=['branch', 'is_active'], name='warehouses__branch__a02157_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'code'), name='unique_warehouse_code_per_branch')],
            },
        ),
    ]
