# Generated by Django 5.2.17 on 2026-09-24 15:16

import apps.organizations.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.organizations.models.default_organization_code, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Use 2-32 characters: A-Z, 0-9, dash or underscore.', regex='^[A-Z0-9][A-Z0-9\\-_]{1,31}$')])),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en', max_length=16)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='organizatio_status_a30a2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Use 2-32 characters: A-Z, 0-9, dash or underscore.', regex='^[A-Z0-9][A-Z0-9\\-_]{1,31}$')])),
                ('name', models.CharField(max_length=150)),
                ('branch_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('branch', 'Branch'), ('distribution_center', 'Distribution center'), ('cross_dock', 'Cross-dock'), ('dark_store', 'Dark store')], default='branch', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['organization__name', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_02ed07_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='unique_branch_code_per_organization')],
            },
        ),
    ]
